### ISSUE TITLE
[feat] please something to support 1.2 roundcube?

### ISSUE THREAD

**Issue by mckaygerhard** [texxasrulez/Roundcube_Skins#3]
there's some way to support roundcube 1.2 or maybe could run this on 1.2 brand of roundcube, 

i cannot upgrade to 1.3 due does not run older browsers, 

please help me in some way i can adapt by myselft but i'm not expert

**Comment by texxasrulez** [comment]
Too much code to make backwards compatible with older versions of RC. Sorry but I do not have the time
