### ISSUE TITLE
[feat] a white (gmail like) colorized skin will be able?

### ISSUE THREAD

**Issue by mckaygerhard** [texxasrulez/Roundcube_Skins#4]
would be nice a white oriented skin, like those that are grey related but more oriented to white, like gmail.. 

as a plus, also a green related too, but that can be combined with white. thanks in advance.

**Comment by texxasrulez** [comment]
I do have plans for many other color schemes but time is not on my side at the moment.

**Comment by mckaygerhard** [comment]
any tip how doit in more easy way, i try it but there's many entries!

**Comment by texxasrulez** [comment]
I am old school and do it with Geany (Notepad ++ Linux clone if not familiar) and I figured it out line by line, so honestly I do not have an easy way to let you know. Best tip I can give you is make a big pot of coffee and get to diggin ... :-)

**Comment by mckaygerhard** [comment]
umm yeah, geany rulez! je je i started just as you said, was hope to find a better faster way but well... thanks any way

**Comment by wesch3al** [comment]
texxasrulez,
I am trying to change some css in the mail.css of Larry. Could you tell me how to update the file after making the css changes.
