### ISSUE TITLE
typo in ALL settingsedit.html

### ISSUE THREAD

**Issue by pikachurus** [texxasrulez/Roundcube_Skins#7]
`<roundcube:button command="save" type="type" class="button mainaction" label="save" />
`
must be:

`<roundcube:button command="save" type="input" class="button mainaction" label="save" />`

**Comment by texxasrulez** [comment]
Thank you for the typo discovery. There is one small change I will make. Instead of  type="input", I am going with type="button". That way instead of a drab grey button, we get the button matched to our color scheme of skins. Again, thank you for you contribution.
